development:
  :address: smtp.rupeevest.com
  :port: 25
  :authentication: plain
  :user_name: info@rupeevest.com
  :password: varuraghinf1
  :enable_starttls_auto: false        

production:
  :address: smtp.rupeevest.com
  :port: 25
  :authentication: plain
  :user_name: info@rupeevest.com
  :password: varuraghinf1
  :enable_starttls_auto: false