development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: varun11us@gmail.com
  :password: papamummy1234
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: varun11us@gmail.com
  :password: papamummy1234
  :enable_starttls_auto: true