require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VisitorsController do

  # This should return the minimal set of attributes required to create a valid
  # Visitor. As you add validations to Visitor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "email" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VisitorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all visitors as @visitors" do
      visitor = Visitor.create! valid_attributes
      get :index, {}, valid_session
      assigns(:visitors).should eq([visitor])
    end
  end

  describe "GET show" do
    it "assigns the requested visitor as @visitor" do
      visitor = Visitor.create! valid_attributes
      get :show, {:id => visitor.to_param}, valid_session
      assigns(:visitor).should eq(visitor)
    end
  end

  describe "GET new" do
    it "assigns a new visitor as @visitor" do
      get :new, {}, valid_session
      assigns(:visitor).should be_a_new(Visitor)
    end
  end

  describe "GET edit" do
    it "assigns the requested visitor as @visitor" do
      visitor = Visitor.create! valid_attributes
      get :edit, {:id => visitor.to_param}, valid_session
      assigns(:visitor).should eq(visitor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Visitor" do
        expect {
          post :create, {:visitor => valid_attributes}, valid_session
        }.to change(Visitor, :count).by(1)
      end

      it "assigns a newly created visitor as @visitor" do
        post :create, {:visitor => valid_attributes}, valid_session
        assigns(:visitor).should be_a(Visitor)
        assigns(:visitor).should be_persisted
      end

      it "redirects to the created visitor" do
        post :create, {:visitor => valid_attributes}, valid_session
        response.should redirect_to(Visitor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved visitor as @visitor" do
        # Trigger the behavior that occurs when invalid params are submitted
        Visitor.any_instance.stub(:save).and_return(false)
        post :create, {:visitor => { "email" => "invalid value" }}, valid_session
        assigns(:visitor).should be_a_new(Visitor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Visitor.any_instance.stub(:save).and_return(false)
        post :create, {:visitor => { "email" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested visitor" do
        visitor = Visitor.create! valid_attributes
        # Assuming there are no other visitors in the database, this
        # specifies that the Visitor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Visitor.any_instance.should_receive(:update).with({ "email" => "MyString" })
        put :update, {:id => visitor.to_param, :visitor => { "email" => "MyString" }}, valid_session
      end

      it "assigns the requested visitor as @visitor" do
        visitor = Visitor.create! valid_attributes
        put :update, {:id => visitor.to_param, :visitor => valid_attributes}, valid_session
        assigns(:visitor).should eq(visitor)
      end

      it "redirects to the visitor" do
        visitor = Visitor.create! valid_attributes
        put :update, {:id => visitor.to_param, :visitor => valid_attributes}, valid_session
        response.should redirect_to(visitor)
      end
    end

    describe "with invalid params" do
      it "assigns the visitor as @visitor" do
        visitor = Visitor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Visitor.any_instance.stub(:save).and_return(false)
        put :update, {:id => visitor.to_param, :visitor => { "email" => "invalid value" }}, valid_session
        assigns(:visitor).should eq(visitor)
      end

      it "re-renders the 'edit' template" do
        visitor = Visitor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Visitor.any_instance.stub(:save).and_return(false)
        put :update, {:id => visitor.to_param, :visitor => { "email" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested visitor" do
      visitor = Visitor.create! valid_attributes
      expect {
        delete :destroy, {:id => visitor.to_param}, valid_session
      }.to change(Visitor, :count).by(-1)
    end

    it "redirects to the visitors list" do
      visitor = Visitor.create! valid_attributes
      delete :destroy, {:id => visitor.to_param}, valid_session
      response.should redirect_to(visitors_url)
    end
  end

end
